# Generated by Django 3.0.2 on 2020-01-15 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_event_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='current_items',
        ),
        migrations.AddField(
            model_name='item',
            name='current_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_items', to='api.Location'),
        ),
    ]
